export default {
  en: {
    addCompany: 'Add company',
    Name: 'Name',
    Projects: 'Projects',
    Offers: 'Offers',
    info: 'Info',
    requisites: 'Requisites',
    documents: 'Documents',
    jurisdiction: 'Jurisdiction',
    selectJurisdiction: 'Select Jurisdiction',
    innOrEquivalent: 'Inn or equivalent',
    enterinnOrEquivalent: 'Enter inn or equivalent',
    ceoFullName: 'Ceo full name',
    enterCeoFullName: 'Enter ceo full name',
    ceoEmail: 'Ceo email',
    enterCeoEmail: 'Enter ceo email',
    ceoTelagram: 'Ceo telagram',
    enterCeoTelagram: 'Enter ceo telagram',
    ceoPhoneNumber: 'Ceo phone number',
    enterCeoPhoneNumber: 'Enter ceo phone number',
    enterClientName: 'Enter name',
    cryptoWallet: 'Crypto wallet',
    enterCryptoWallet: 'Enter crypto wallet',
    fiatSwift: 'Fiat SWIFT',
    enterFiatSwift: 'Enter Fiat SWIFT',
    fiatAccountNumber: 'Fiat account number',
    enterFiatAccountNumber: 'Enter fiat account number',
    fiatBankName: 'Fiat bank name',
    enterFiatBankName: 'Enter fiat bank name',
    fiatBankInn: 'Fiat bank inn',
    enterFiatBankInn: 'Enter fiat bank Inn',
    fiatBankBik: 'Fiat bank bik',
    enterFiatBankBik: 'Enter fiat bank bik',
    fiatBankKpp: 'Fiat bank kpp',
    enterfiatBankKpp: 'Enter fiat bank kpp',
    confirmDeleteCompany: 'Are you sure you want to delete this client ?',
  },
  ru: {
    addCompany: 'Добавить компанию',
    Name: 'Имя',
    Projects: 'Проекты',
    Offers: 'Офферы',
    info: 'Инфо',
    requisites: 'Реквизиты',
    documents: 'Документы',
    jurisdiction: 'Юрисдикция',
    selectJurisdiction: 'Выберите юрисдикцию',
    innOrEquivalent: 'ИНН или эквивалент',
    enterinnOrEquivalent: 'Введите ИНН или эквивалент',
    ceoFullName: 'ФИО генерального директора',
    enterCeoFullName: 'Введите ФИО генерального директора',
    ceoEmail: 'Email генерального директора',
    enterCeoEmail: 'Введите email генерального директора',
    ceoTelagram: 'Telegram генерального директора',
    enterCeoTelagram: 'Введите Telegram генерального директора',
    ceoPhoneNumber: 'Телефон генерального директора',
    enterCeoPhoneNumber: 'Введите телефон генерального директора',
    enterClientName: 'Введите имя',
    cryptoWallet: 'Криптокошелек',
    enterCryptoWallet: 'Введите криптокошелек',
    fiatSwift: 'Фиатный SWIFT',
    enterFiatSwift: 'Введите фиатный SWIFT',
    fiatAccountNumber: 'Фиатный номер счета',
    enterFiatAccountNumber: 'Введите фиатный номер счета',
    fiatBankName: 'Название фиатного банка',
    enterFiatBankName: 'Введите название фиатного банка',
    fiatBankInn: 'ИНН фиатного банка',
    enterFiatBankInn: 'Введите ИНН фиатного банка',
    fiatBankBik: 'БИК фиатного банка',
    enterFiatBankBik: 'Введите БИК фиатного банка',
    fiatBankKpp: 'КПП фиатного банка',
    enterfiatBankKpp: 'Введите КПП фиатного банка',
    confirmDeleteCompany: 'Вы уверены, что хотите удалить этого клиента?',
  },
};
