export default {
  en: {
    department: 'Department',
    remove: 'Remove',
    addDepartment: 'Add Department',
    cancel: 'Cancel',
    save: 'Save',
    role: 'Role',
    quantity: 'Quantity',
    addRole: 'Add role',
    selectRole: 'Select a role',
    selectDepartment: 'Select a department',
    workingDays: 'wd',
    selectLoad: 'Select a scheduled load',
  },
  ru: {
    department: 'Департамент',
    remove: 'Удалить',
    addDepartment: 'Добавить департамент',
    cancel: 'Отмена',
    save: 'Сохранить',
    role: 'Роль',
    quantity: 'Количество',
    addRole: 'Добавить роль',
    selectRole: 'Выберите роль',
    selectDepartment: 'Выберите департамент',
    workingDays: 'рд',
    selectLoad: 'Выберите запланированную нагрузку',
  },
};
