export default {
  en: {
    fullName: 'Full Name',
    telegram: 'Telegram',
    daysInCompany: 'Days In Company',
    timeZone: 'Timezone',
    avatar: 'Avatar',
    isActive: 'Is Active',
    email: 'Email',
    telegramAccount: 'Telegram Account',
    phoneNumber: 'Phone Number',
    cityOfResidence: 'City Of Residence',
    entranceDate: 'Entrance Date',
    affiliation: 'Affiliation',
    forceDeactivation: 'Force Deactivation',
    dateOfDismissal: 'Date of Dismissal',
    citizenship_1: 'Citizenship 1',
    citizenship_2: 'Citizenship 2',
    selectEntranceDate: 'Select entrance date',
    selectCityOfResidence: 'Select city of residence',
    enterTelegramAccount: 'Enter Telegram Account',
    enterPhoneNumber: 'Enter phone number',
    selectAffliation: 'Select affiliation',
    selectDateOfDismissal: 'Select date of dismissal',
    selectCitizenship1: 'Select citizenship 1',
    selectCitizenship2: 'Select citizenship 2',
    helpTextForceDeactivation:
      'If ticked, the employee is deleted from the system no matter if it is active in Jira or not. Otherwise, the employee presence in the system becomes fully controlled by Jira',
    selectAffiliationType: 'Select affiliation type',
    helpTextForceDeactivationProject:
      'If ticked, the project is deleted from the system no matter if it is active in Jira or not. Otherwise, the project presence in the system becomes fully controlled by Jira',
    selectActivity: 'Select activity',
    active: 'Active',
    archived: 'Archived',
    all: 'All',
    searchByNameOrTelegram: 'Search by name or telegram',
    cryptoWalletNumber: '(USDT TRX) Crypto wallet number',
    fiatAccountNumber: 'Fiat account number',
    correspondentAccount: 'Correspondent account',
    bankName: 'Bank name',
    bankInn: 'Bank INN',
    bankBik: 'Bank BIK',
    bankKpp: 'Bank KPP',
    enterRemuneration: 'Enter Remuneration',
    enterCryptoWalletNumber: 'Enter Crypto wallet number',
    enterFiatAccountNumber: 'Enter Fiat account number',
    enterCorrespondentAccount: 'Enter correspondent account',
    enterBankName: 'Enter bank name',
    enterBankInn: 'Enter bank INN',
    enterBankBik: 'Enter bank BIK',
    enterBankKpp: 'Enter bank KPP',
    remindAboutMissingHours: 'Remind about missing hours',
    showLastSixMonthsTrackedHours: 'Last 6 months tracked hours',
    accumulatedVacationDays: 'Accumulated vacation days',
    usedVacationDays: 'Used vacation days',
    unusedVacationDays: 'Unused vacation days',
    plannedVacationDays: 'Planned vacation days',
    totalDayOffsLastSixMonths: 'Total day-offs last six months',
    areVacationsApproved: 'Are the vacations approved',
    calculated_remuneration: 'Renumeration',
    currency: 'Currency',
    payment_type: 'Payment type',
    employment_type: 'Employement type',
    company: 'Company',
    selectSalaryType: 'Select salary type',
    selectCompanyCurrency: 'Select company currency',
    selectEmploymentType: 'Select employment type',
    selectCompany: 'Select company',
    selectPaymentType: 'Select payment type',
    selectCurrency: 'Select currency',
    remuneration: 'Remuneration',
    hourly_rate__usd: 'Hourly rate USD',
    hourly_rate__rub: 'Hourly rate RUB',
    hourly_rate__eur: 'Hourly rate EUR',
    monthly_rate__usd: 'Monthly rate USD',
    monthly_rate__rub: 'Monthly rate RUB',
    monthly_rate__eur: 'Monthly rate EUR',
    addAnotherDocument: 'Add another document',
    documents: 'Documents',
    document: 'Document',
    searchByName: 'Search by name',
    personalInfo: 'Personal info',
    requisites: 'Requisites',
    metrics: 'Metrics',
    preferences: 'Preferences',
    finance: 'Finance',
    gross: 'Gross',
    net: 'Net',
    date: 'Date',
    remunerationNet: 'Remuneraton (net)',
    salaryFor: 'Salary for',
  },
  ru: {
    fullName: 'Полное имя',
    telegram: 'Телеграм',
    daysInCompany: 'Дней в компании',
    timeZone: 'Часовой пояс',
    avatar: 'Аватар',
    isActive: 'Активен',
    email: 'Электронная почта',
    telegramAccount: 'Аккаунт Telegram',
    phoneNumber: 'Номер телефона',
    cityOfResidence: 'Город проживания',
    entranceDate: 'Дата поступления',
    affiliation: 'Принадлежность',
    forceDeactivation: 'Принудительная деактивация',
    dateOfDismissal: 'Дата увольнения',
    citizenship_1: 'Гражданство 1',
    citizenship_2: 'Гражданство 2',
    selectEntranceDate: 'Выберите дату поступления',
    selectCityOfResidence: 'Выберите город проживания',
    enterTelegramAccount: 'Введите аккаунт Telegram',
    enterPhoneNumber: 'Введите номер телефона',
    selectAffliation: 'Выберите аффилиацию',
    selectDateOfDismissal: 'Выберите дату увольнения',
    selectCitizenship1: 'Выберите гражданство 1',
    selectCitizenship2: 'Выберите гражданство 2',
    helpTextForceDeactivation:
      'Если данная опция включена, то сотрудник удаляется из системы вне зависимости от его статуса в Jira. Если же опция выключена, то статус сотрудника в системе будет соответствовать его статусу в Jira',
    helpTextForceDeactivationProject:
      'Если данная опция включена, то проект удаляется из системы вне зависимости от его статуса в Jira. Если же опция выключена, то статус проекта в системе будет соответствовать его статусу в Jira',
    selectAffiliationType: 'Выберите тип принадлежности',
    selectActivity: 'Выберите активность',
    searchByNameOrTelegram: 'Поиск по имени или Телеграму',
    cryptoWalletNumber: '(USDT TRX) Номер криптокошелька',
    fiatAccountNumber: 'Номер фиатного счета',
    correspondentAccount: 'Корреспондентский счет',
    bankName: 'Название банка',
    bankInn: 'ИНН банка',
    bankBik: 'БИК банка',
    bankKpp: 'КПП банка',
    enterCryptoWalletNumber: 'Введите номер криптокошелька',
    enterFiatAccountNumber: 'Введите номер фиатного счета',
    enterCorrespondentAccount: 'Введите корреспондентский счет',
    enterBankName: 'Введите название банка',
    enterBankInn: 'Введите ИНН банка',
    enterBankBik: 'Введите БИК банка',
    enterBankKpp: 'Введите КПП банка',
    enterRemuneration: 'Введите вознаграждение',
    remindAboutMissingHours: 'Напомнить о недостающих часах',
    showLastSixMonthsTrackedHours: 'Отслеженные часы за последние 6 месяцев',
    accumulatedVacationDays: 'Накопленные дни отпуска',
    usedVacationDays: 'Отгуленные дни отпуска',
    unusedVacationDays: 'Неиспользованные дни отпуска',
    plannedVacationDays: 'Запланированные дни отпуска',
    totalDayOffsLastSixMonths:
      'Общее количество выходных за последние 6 месяцев',
    areVacationsApproved: 'Одобрен ли отпуск',
    calculated_remuneration: 'Вознаграждение',
    currency: 'Валюта',
    payment_type: 'Тип выплаты',
    employment_type: 'Тип занятости',
    company: 'Компания',
    selectSalaryType: 'Выберите тип зарплаты',
    selectCompanyCurrency: 'Выберите валюту компании',
    selectEmploymentType: 'Выберите тип занятости',
    selectCompany: 'Выберите компанию',
    selectPaymentType: 'Выберите тип оплаты',
    selectCurrency: 'Выберите валюту',
    remuneration: 'Вознаграждение',
    hourly_rate__usd: 'Часовая ставка USD',
    hourly_rate__rub: 'Часовая ставка RUB',
    hourly_rate__eur: 'Часовая ставка EUR',
    monthly_rate__usd: 'Ежемесячная ставка USD',
    monthly_rate__rub: 'Ежемесячная ставка RUB',
    monthly_rate__eur: 'Ежемесячная ставка EUR',
    addAnotherDocument: 'Добавить еще один Документ',
    documents: 'Документы',
    document: 'Документ',
    searchByName: 'Поиск по имени',
    active: 'Активный',
    archived: 'Архивированный',
    all: 'Все',
    personalInfo: 'Личная информация',
    requisites: 'Реквизиты',
    metrics: 'Метрики',
    preferences: 'Предпочтения',
    finance: 'Финансы',
    gross: 'Gross',
    net: 'Net',
    date: 'Дата',
    remunerationNet: 'Вознаграждение (net)',
    salaryFor: 'Зарплата для',
  },
};
