export default {
  en: {
    edit_aldan_rate: 'Edit Aldan rate for',
    edit_currency_rate: 'Edit currency rate for',
    financialModels: 'Financial models',
    usd_current_rate: 'USD current rate',
    eur_current_rate: 'EUR current rate',
    usd_aldan_modifier: 'USD Aldan modifier',
    eur_aldan_modifier: 'EUR Aldan modifier',
    usd_aldan_rate: 'USD Aldan rate',
    eur_aldan_rate: 'EUR Aldan rate',
    usd_average_rate: 'USD average rate',
    eur_average_rate: 'EUR average rate',
    enterUsdAldanModifier: 'Enter USD aldan modifier',
    enterEurAldanModifier: 'Enter EUR aldan modifier',
    currencyRates: 'Currency Rates',
    help_text_current_rate: 'Recalculated once per day for the current month',
    help_text_usd_aldan_modifier:
      'Modifier used to calculate USD Aldan rate (percentage). Set by user.',
    help_text_eur_aldan_modifier:
      'Modifier used to calculate EUR Aldan rate (percentage). Set by user.',
    help_text_usd_aldan_rate:
      'Average USD rate in the given calendar month multiplied by Aldan modifier',
    help_text_eur_aldan_rate:
      'Average EUR rate in the given calendar month multiplied by Aldan modifier',
    help_text_usd_average_rate: 'Average USD rate in the given calendar month',
    help_text_eur_average_rate: 'Average EUR rate in the given calendar month',
    aldanFixedRates: 'Aldan Fixed Rates',
    usd_previous_month_currency_fixed_rate:
      'Previous month USD Aldan rate(RUB)',
    eur_previous_month_currency_fixed_rate:
      'Previous month EUR Aldan rate (RUB)',
    insurance_premiums: 'Insurance premiums (%)',
    personal_income_tax: 'Personal income tax (%)',
    total_expenses: 'Total expenses (RUB)',
    income_flex: 'Income flex (%)',
    income_fix: 'Income fix (RUB)',
    utilization_rate: 'Utilization rate (%)',
    help_text_usd_aldan_fixed_rate: "Last month's average USD rate",
    help_text_eur_aldan_fixed_rate: "Last month's average EUR rate",
    help_text_insurance_premiums: 'Insurance premiums',
    help_text_personal_income_tax: 'Personal income tax',
    help_text_total_expenses: 'Total expenses',
    help_text_income_flex: 'Income flex',
    help_text_income_fix: 'Income fix',
    help_text_utilization_rate: 'Utilization rate',
    cancel: 'Cancel',
    confirm: 'Confirm',
    roundToInteger: 'Round to integer',
    roundRub: 'Round RUB',
  },
  ru: {
    edit_aldan_rate: 'Редактировать ставку Aldan за',
    edit_currency_rate: 'Редактировать курс за',
    financialModels: 'Финансовые модели',
    usd_current_rate: 'Текущий курс USD',
    eur_current_rate: 'Текущий курс EUR',
    usd_aldan_modifier: 'Модификатор USD Aldan',
    eur_aldan_modifier: 'Модификатор EUR Aldan',
    usd_aldan_rate: 'Курс USD Aldan',
    eur_aldan_rate: 'Курс EUR Aldan',
    usd_average_rate: 'Средний курс USD',
    eur_average_rate: 'Средний курс EUR',
    enterUsdAldanModifier: 'Введите модификатор USD Aldan',
    enterEurAldanModifier: 'Введите модификатор EUR Aldan',
    currencyRates: 'Валютные курсы',
    help_text_current_rate:
      'Перерасчитывается один раз в день для текущего месяца',
    help_text_usd_aldan_modifier:
      'Коэффициент для расчета курса USD Aldan. Задается пользователем.',
    help_text_eur_aldan_modifier:
      'Коэффициент для расчета курса EUR Aldan. Задается пользователем.',
    help_text_usd_aldan_rate:
      'Усредненный курс USD в данном календарном месяце, умноженный на модификатор Aldan',
    help_text_eur_aldan_rate:
      'Усредненный курс EUR в данном календарном месяце, умноженный на модификатор Aldan',
    help_text_usd_average_rate:
      'Усредненный курс USD в данном календарном месяце',
    help_text_eur_average_rate:
      'Усредненный курс EUR в данном календарном месяце',
    aldanFixedRates: 'Курсы Aldan',
    usd_previous_month_currency_fixed_rate:
      'Курс USD Aldan за прошлый месяц (RUB)',
    eur_previous_month_currency_fixed_rate:
      'Курс EUR Aldan за прошлый месяц (RUB)',
    insurance_premiums: 'Страховые взносы (%)',
    personal_income_tax: 'НДФЛ (%)',
    total_expenses: 'Общие расходы (RUB)',
    income_flex: 'Доход flex (%)',
    income_fix: 'Доход fix (RUB)',
    utilization_rate: 'Коэффициент утилизации (%)',
    help_text_usd_aldan_fixed_rate: 'Усредненный курс USD за прошлый месяц',
    help_text_eur_aldan_fixed_rate: 'Усредненный курс EUR за прошлый месяц',
    help_text_insurance_premiums: 'Страховые взносы',
    help_text_personal_income_tax: 'НДФЛ',
    help_text_total_expenses: 'Общие расходы',
    help_text_income_flex: 'Доход flex',
    help_text_income_fix: 'Доход fix',
    help_text_utilization_rate: 'Коэффициент утилизации',
    cancel: 'Отмена',
    confirm: 'Подтвердить',
    roundToInteger: 'Округлить до целых чисел',
    roundRub: 'Округлить рубли',
  },
};
