export default {
  en: {
    loading: 'Loading...',
    selectOption: 'Select option',
    back: 'Back',
    selectYear: 'Select year',
    selectMonth: 'Select month',
    selectProject: 'Select project',
    selectCategory: 'Select category',
    selectOffer: 'Select offer',
    selectEmployee: 'Select an Employee',
    pageNotReady: 'Page under construction',
    underConstruction: 'Under construction',
    deleteItem: 'Are you sure you want to delete this item?',
    oops: 'Ooops, something went wrong',
    cancel: 'Cancel',
    search: 'Search',
    syncing: 'Syncing',
    synced: 'Synced',
    delete: 'Delete',
    enterLink: 'Enter link',
    visitLink: 'Visit the link',
  },
  ru: {
    loading: 'Загрузка...',
    selectOption: 'Выберите опцию',
    back: 'Назад',
    selectYear: 'Выберите год',
    selectMonth: 'Выберите месяц',
    selectProject: 'Выберите проект',
    selectOffer: 'Выберите оффер',
    selectCategory: 'Выберите категорию',
    selectEmployee: 'Выберите сотрудника',
    pageNotReady: 'Страница в разработке',
    underConstruction: 'В разработке',
    deleteItem: 'Вы уверены, что хотите удалить этот элемент?',
    oops: 'Ой, что-то пошло не так',
    cancel: 'Отмена',
    search: 'Поиск',
    syncing: 'Синхронизация',
    synced: 'Синхронизировано',
    delete: 'Удалить',
    enterLink: 'Введите ссылку',
    visitLink: 'Перейти',
  },
};
