export default {
  en: {
    totals: 'Totals',
    from: 'From (only Monday is allowed) ',
    to: 'To',
    workingDays: 'Working days',
    period: 'Period',
    kpi: 'KPI',
    bonus: 'Bonus',
    switchToStagesView: 'Roles view',
    switchToGanttView: 'Gantt view',
    week: 'Week',
    taskDescription: 'Task description',
    addTaskDescription: 'Add description',
    hours: 'h',
    addRoleForStage: 'Add role to stage',
    addRole: 'Add role',
    enterStageName: 'Enter stage name',
    tariffRateDate: 'Tariff rate date',
    enterKpi: 'Enter KPI',
    enterBonus: 'Enter bonus',
    selectDate: 'Select date',
    offerName: 'Title',
    offerTitleName: 'Offer',
    status: 'Status',
    project: 'Project',
    updatedAt: 'Updated at',
    terminationDate: 'Termination date',
    monthsDuration: 'Project duration (in months)',
    offerComment: 'Project description',
    associateWithProject: 'Associate with project',
    financialSource: 'Financial sources',
    rolesAndStages: 'Roles and stages',
    aggregates: 'Aggregates',
    company: 'Company',
    author: 'Author',
    rateCalculationReferenceDate: 'Rate calculation reference date',
    createdAt: 'Created at',
    enterComment: 'Enter comment',
    client: 'Client',
    tariff: 'Tariff',
    fundingShare: 'Funding share',
    equity: 'Equity',
    addOffer: 'Add offer',
    addFinancialSource: 'Add financial source',
    selectClient: 'Select client',
    selectTariff: 'Select tariff',
    funding_share: 'Funding share',
    enterFundingShare: 'Enter funding share',
    enterEquity: 'Enter equity',
    confirmDeleteOffer: 'Are you sure to delete this offer?',
    enterOfferName: 'Enter title',
    selectCompany: 'Select company',
    enterMonthDuration: 'Enter month duration',
    selectStatus: 'Select status',
    offerHasNoStages: 'Offer has no stages',
    editRole: '{role} ({stageName})',
    editEmployeeStageRole: '{name} ({role},\n {stageName})',
    offerHasNoProject: 'Offer has no associated project',
    deletingRole: 'Deleting the role',
    deletedRole: 'The role is deleted',
    in: 'in',
  },
  ru: {
    totals: 'Итого',
    from: 'От (разрешён только понедельник)',
    to: 'До',
    workingDays: 'Рабочие дни',
    period: 'Период',
    kpi: 'KPI',
    bonus: 'Бонус',
    switchToStagesView: 'Роли',
    switchToGanttView: 'Диаграмма Ганта',
    week: 'Неделя',
    taskDescription: 'Описание задачи',
    addTaskDescription: 'Добавить описание',
    hours: 'ч',
    addRole: 'Добавить роль',
    addRoleForStage: 'Добавить роль на этап',
    enterStageName: 'Введите название этапа',
    tariffRateDate: 'Дата тарифной ставки',
    enterKpi: 'Введите KPI',
    enterBonus: 'Введите бонус',
    selectDate: 'Выберите дату',
    offerName: 'Название',
    offerTitleName: 'Оффер',
    status: 'Статус',
    project: 'Проект',
    updatedAt: 'Обновлено',
    terminationDate: 'Дата завершения',
    monthsDuration: 'Продолжительность проекта (в мес.)',
    financialSource: 'Финансовые источники',
    rolesAndStages: 'Роли и этапы',
    aggregates: 'Агрегаты',
    company: 'Компания',
    author: 'Автор',
    rateCalculationReferenceDate: 'Референтная дата для расчета тарифа',
    createdAt: 'Дата создания',
    enterComment: 'Введите комментарий',
    client: 'Клиент',
    tariff: 'Тариф',
    fundingShare: 'Доля финансирования',
    addOffer: 'Добавить оффер',
    addFinancialSource: 'Добавить финансовый источник',
    selectClient: 'Выберите клиента',
    selectTariff: 'Выберите тариф',
    funding_share: 'Доля финансирования',
    equity: 'Капитал',
    enterFundingShare: 'Введите долю финансирования',
    enterEquity: 'Введите капитал',
    confirmDeleteOffer: 'Вы уверены, что хотите удалить этот оффер?',
    enterOfferName: 'Введите название',
    offerComment: 'Описание проекта',
    associateWithProject: 'Ассоциировать с проектом',
    selectCompany: 'Выберите компанию',
    enterMonthDuration: 'Введите продолжительность в месяцах',
    selectStatus: 'Выберите статус',
    offerHasNoStages: 'Оффер не имеет этапов',
    editRole: '{role} ({stageName})',
    editEmployeeStageRole: '{name} ({role},\n {stageName})',
    offerHasNoProject: 'Оффер не связан с проектом',
    deletingRole: 'Удаление роли',
    deletedRole: 'Роль удалена',
    in: 'в',
  },
};
