export default {
  en: {
    addOperationalExpense: 'Add operational expense',
    totalAmount: 'Total amount',
    updatedAt: 'Updated at',
    notSpecified: 'N/O',
    infinite: 'Infinite',
    oneTime: 'One-time',
    amount: 'Amount',
    opexSearch: 'Search',
    perMonth: 'Per month',
    forSelectedPeriod: 'For the selected period',
    forAllTime: 'For all time',
    totalAmountGroupedByCurrencyOfDenomination:
      'Total amount for the selected period, grouped by currency denomination',
    totalAmountInAllCurrenciesConvertedTo:
      'Total amount for the selected period, converted across all currencies',
    period: 'Period',
    recurrence_period: 'Recurrence',
    currency: 'Currency',
    name: 'Name',
    category: 'Category',
    card: 'Card',
    projectName: 'Project',
    offerName: 'Offer',
    thisMonth: 'This month',
    lastMonth: 'Last month',
    thisYear: 'This year',
    lastYear: 'Last year',
    selectFromDate: 'Select start date',
    selectToDate: 'Select end date',
    opexDateHelpTextForAllTime: 'Opex for all time',
    opexDateHelpTextForMonth: 'Opex for  {date}',
    opexDateHelpTextForPeriod: 'Opex for the period between  {from}  and  {to}',
  },
  ru: {
    addOperationalExpense: 'Добавить операционный расход',
    totalAmount: 'Общая сумма',
    updatedAt: 'Обновлено в',
    notSpecified: 'Н/0',
    infinite: 'Бесконечный',
    oneTime: 'Единоразовый',
    amount: 'Сумма',
    opexSearch: 'Поиск',
    perMonth: 'За месяц',
    forSelectedPeriod: 'За выбранный период',
    forAllTime: 'За всё время',
    totalAmountGroupedByCurrencyOfDenomination:
      'Общая сумма за выбранный период, сгруппированая по валюте номинала',
    totalAmountInAllCurrenciesConvertedTo:
      'Общая сумма за выбранный период, конвертированная по всем валютам',
    period: 'Период',
    recurrence_period: 'Период рекуррентности',
    currency: 'Валюта',
    name: 'Название',
    category: 'Категория',
    card: 'Карта',
    projectName: 'Проект',
    offerName: 'Оффер',
    thisMonth: 'Этот месяц',
    lastMonth: 'Прошлый месяц',
    thisYear: 'Этот год',
    lastYear: 'Прошлый год',
    selectFromDate: 'Выберите дату начала',
    selectToDate: 'Выберите дату окончания',
    opexDateHelpTextForAllTime: 'Opex за всё время',
    opexDateHelpTextForMonth: 'Opex за  {date}',
    opexDateHelpTextForPeriod: 'Opex за период  {from}  по  {to}',
  },
};
