export default {
  en: {
    roles: 'Roles',
    employee: 'Employee',
    scheduledLoad: 'Scheduled load',
    role: 'Role',
    department: 'Department',
    offer: 'Offer',
    status: 'Status',
    stage: 'Stage',
    activeFromTo: 'Active(from-to)',
    boundToOffer: 'Bound to offer',
    workingHours: 'Working hours',
    addRole: 'Add role',
    addRoleDescription: '{role} ({stageName})',
    employmentType: 'Employment type',
    hourlyRate: 'Hourly rate',
    activationDate: 'Activation date',
    deactivationDate: 'Deactivation date',
    selectEmploymentType: 'Select employment type',
    selectEmployee: 'Select employee',
    selectRole: 'Select role',
    selectActivationDate: 'Select activation date',
    selectDeactivationDate: 'Select deactivation date',
    checkbox: 'Take roles from the offer',
    stageName: 'Stage',
    add: 'Add',
    manageOfferRoles: 'Manage roles in offer',
    addEmployeeToStage: 'Add employee to {role} ({stageName})',
    period: 'Period',
    startDate: 'Start date',
    endDate: 'End date',
    present: 'Present',
    active: 'Active',
    all: 'All',
    deletingEmployeeRole: 'Deleting employee role',
    deletedEmployeeRole: 'Deleted employee role',
  },
  ru: {
    roles: 'Роли',
    employee: 'Сотрудник',
    scheduledLoad: 'Запланированная нагрузка',
    department: 'Отдел',
    offer: 'Оффер',
    status: 'Статус',
    stage: 'Этап',
    activeFromTo: 'Активен (с - по)',
    boundToOffer: 'С привязкой к офферу',
    workingHours: 'Рабочие часы',
    addRole: 'Добавить роль',
    addRoleDescription: '{role} ({stageName})',
    role: 'Роль',
    employmentType: 'Тип занятости',
    hourlyRate: 'Почасовая ставка',
    activationDate: 'Дата активации',
    deactivationDate: 'Дата деактивации',
    selectEmploymentType: 'Выберите тип занятости',
    selectEmployee: 'Выберите сотрудника',
    selectRole: 'Выберите роль',
    selectActivationDate: 'Выберите дату активации',
    selectDeactivationDate: 'Выберите дату деактивации',
    checkbox: 'Взять роли из оффера',
    add: 'Добавить',
    manageOfferRoles: 'Управление ролями в оффере',
    addEmployeeToStage: 'Добавить сотрудника на {role} ({stageName})',
    period: 'Период',
    startDate: 'Дата начала',
    endDate: 'Дата окончания',
    present: 'Настоящее время',
    active: 'Активный',
    all: 'Все',
    deletingEmployeeRole: 'Удаление роли сотрудника',
    deletedEmployeeRole: 'Роль сотрудника удалена',
  },
};
