export default {
  en: {
    name: 'Name',
    code: 'Code',
    category: 'Category',
    offer: 'Offer',
    lead: 'Lead',
    telegramChat: 'Telegram chat',
    isActive: 'Is active',
    forceDeactivation: 'Force Deactivation',
    helpTextForceDeactivation:
      'If ticked, the employee is deleted from the system no matter if it is active in Jira or not. Otherwise, the employee presence in the system becomes fully controlled by Jira',
    selectActivity: 'Select activity',
    clientName: 'Client',
    startDate: 'Start date',
    trackedHours: 'Tracked hours',
    deletedAt: 'Deleted at',
    general: 'General',
    documents: 'Documents',
    document: 'Document',
    addAnotherDocument: 'Add another document',
    financingSource: 'Financing Source',
    total: 'Total',
    plan: 'Plan',
    tariffRateNotice: 'Rates are taken as of:',
    payrollFund: 'Payroll fund',
    invoice: 'Invoice amount',
    real: 'Real expenses',
    realTabName: 'Real',
    overall: 'Overall',
    summary: 'Summary',
    noData: 'No data',
    projectPayments: 'Project payments',
    projectActivityType: 'Active/All toggle for project',
  },
  ru: {
    name: 'Имя',
    code: 'Код',
    category: 'Категория',
    offer: 'Оффер',
    lead: 'Руководитель',
    telegramChat: 'Telegram чат',
    isActive: 'Активен',
    forceDeactivation: 'Принудительная деактивация',
    helpTextForceDeactivation:
      'Если данная опция включена, то сотрудник удаляется из системы вне зависимости от его статуса в Jira. Если же опция выключена, то статус сотрудника в системе будет соответствовать его статусу в Jira',
    selectActivity: 'Выберите активность',
    clientName: 'Клиент',
    startDate: 'Дата начала',
    trackedHours: 'Затреканные часы',
    deletedAt: 'Удален в',
    general: 'Основная информация',
    documents: 'Документы',
    document: 'Документ',
    addAnotherDocument: 'Добавить еще один Документ',
    financingSource: 'Источник финансирования',
    total: 'Итого',
    plan: 'План',
    tariffRateNotice: 'Тарифы взяты по состоянию на:',
    payrollFund: 'ФОТ',
    invoice: 'Сумма инвойса',
    real: 'Реальные затраты',
    realTabName: 'ФОТ',
    overall: 'Общий',
    noData: 'Нет данных',
    summary: 'Итоги',
    projectPayments: 'Платежи по проектам',
    projectActivityType: 'Переключатель активных/всех проектов',
  },
};
