export default {
  en: {
    mainPage: 'Main Page',
    opex: 'OPEX',
    offers: 'Offers',
    vacations: 'Vacations',
    employees: 'Employees',
    projects: 'Projects',
    hr: 'HR',
    salarySheet: 'Salary sheet',
    accounting: 'Accounting',
    reports: 'Reports',
    companies: 'Companies',
    finance: 'Finance',
    currencyRates: 'Currency Rates',
    aldanFixedRates: 'Aldan fixed rates',
    cards: 'Cards',
    tariffRates: 'Tariff Rates',
    byUser: 'By user',
    byProject: 'By project',
    byDepartment: 'By department',
    trakcedHours: 'Tracked hours',
  },
  ru: {
    mainPage: 'Главная страница',
    opex: 'OPEX',
    offers: 'Офферы',
    vacations: 'Отпуска',
    employees: 'Сотрудники',
    projects: 'Проекты',
    hr: 'HR',
    salarySheet: 'Зарплата',
    accounting: 'Аккаунтинг',
    reports: 'Отчеты',
    companies: 'Компании',
    finance: 'Finance',
    currencyRates: 'Валютные курсы',
    aldanFixedRates: 'Фиксированные курсы Aldan',
    cards: 'Карты',
    tariffRates: 'Тарифные ставки',
    byUser: 'По пользователю',
    byProject: 'По проекту',
    byDepartment: 'По департаменту',
    trakcedHours: 'Затреканные часы',
  },
};
