export default {
  en: {
    addTariffRate: 'Add tariff rate',
    role: 'Role',
    selectRole: 'Select a role',
    rateRub: 'Rate RUB',
    rateUsd: 'Rate USD',
    rateEur: 'Rate EUR',
    enterRateRub: 'Enter rate RUB',
    enterRateUsd: 'Enter rate USD',
    enterRateEur: 'Enter rate EUR',
    minimalRub: 'Minimal RUB',
    enterMinimalRub: 'Enter minimal RUB',
    minimalUsd: 'Minimal USD',
    enterMinimalUsd: 'Enter minimal USD',
    minimalEur: 'Minimal EUR',
    enterMinimalEur: 'Minimal EUR',
    costRub: 'Cost RUB',
    enterCostRub: 'Enter cost RUB',
    costUsd: 'Cost USD',
    enterCostUsd: 'Enter cost USD',
    costEur: 'Cost EUR',
    enterCostEur: 'Enter cost EUR',
    developmentRub: 'Development RUB',
    enterdevelopmentRub: 'Enter development RUB',
    developmentUsd: 'Development USD',
    enterdevelopmentUsd: 'Enter development USD',
    developmentEur: 'Development EUR',
    enterdevelopmentEur: 'Enter development EUR',
    profitRub: 'Profit RUB',
    enterprofitRub: 'Enter profit RUB',
    profitUsd: 'Profit USD',
    enterprofitUsd: 'Enter profit USD',
    profitEur: 'Profit EUR',
    enterprofitEur: 'Enter profit EUR',
    rubPerMonth: 'RUB per month',
    rub: 'RUB',
    usd: 'USD',
    eur: 'EUR',
    tariff1Title: 'Tariff 1(Cost project)',
    tariff2Title: 'Tariff 2 (Cost company)',
    tariff3Title: 'Tariff 3 (Profit)',
    editTariffRateForRole: 'Edit tariff rate for role',
    rubPerMonthHelpText: '',
    rubHelpText: '',
    usdHelpText: '',
    eurHelpText: '',
  },
  ru: {
    addTariffRate: 'Добавить тарифную ставку',
    selectRole: 'Выберите роль',
    rateRub: 'Ставка RUB',
    rateUsd: 'Ставка USD',
    rateEur: 'Ставка EUR',
    enterRateRub: 'Введите ставку RUB',
    enterRateUsd: 'Введите ставку USD',
    enterRateEur: 'Введите ставку EUR',
    minimalRub: 'Минимум RUB',
    enterMinimalRub: 'Введите минимум RUB',
    minimalUsd: 'Минимум USD',
    enterMinimalUsd: 'Введите минимум USD',
    minimalEur: 'Минимум EUR',
    enterMinimalEur: 'Введите минимум EUR',
    costRub: 'Стоимость RUB',
    enterCostRub: 'Введите стоимость RUB',
    costUsd: 'Стоимость USD',
    enterCostUsd: 'Введите стоимость USD',
    costEur: 'Стоимость EUR',
    enterCostEur: 'Введите стоимость EUR',
    developmentRub: 'Разработка RUB',
    enterdevelopmentRub: 'Введите разработку RUB',
    developmentUsd: 'Разработка USD',
    enterdevelopmentUsd: 'Введите разработку USD',
    developmentEur: 'Разработка EUR',
    enterdevelopmentEur: 'Введите разработку EUR',
    profitRub: 'Прибыль RUB',
    enterprofitRub: 'Введите прибыль RUB',
    profitUsd: 'Прибыль USD',
    enterprofitUsd: 'Введите прибыль USD',
    profitEur: 'Прибыль EUR',
    enterprofitEur: 'Введите прибыль EUR',
    grade: 'Грейд',
    rubPerMonth: 'RUB в месяц',
    rub: 'RUB',
    usd: 'USD',
    eur: 'EUR',
    tariff1Title: 'Тариф 1 (Себестоимость проекта)',
    tariff2Title: 'Тариф 2 (Себестоимость компании)',
    tariff3Title: 'Тариф 3 (Прибыль)',
    editTariffRateForRole: 'Редактировать тарифную ставку для роли',
    rubPerMonthHelpText: '',
    rubHelpText: '',
    usdHelpText: '',
    eurHelpText: '',
  },
};
