export default {
  en: {
    vacation: 'Vacation',
    sickLeave: 'Sick leave',
    dayOff: 'Day-off',
    halfDayOff: 'Half day-off',
    workOff: 'Work-off',
    holiday: 'Non-business day',
    'sick-leave': 'Sick leave',
    'day-off': 'Day-off',
    'half-day-off': 'Half day-off',
    'work-off': 'Work-off',
    add: 'Add',
    employeeName: 'Employee name',
    vacationType: 'Vacation type',
    noVacations: 'No active vacations',
    selectVacationType: 'Select vacation type',
    addSickLeave: 'Sick leave',
    addVacation: 'Vacation',
    addDayOff: 'Day-off',
    addHalfDayOff: 'Half a day off',
    employee: 'Employee',
    status: 'Status',
    selectVacationStatus: 'Select vacation status',
    created: 'Created at',
    updated: 'Updated at',
    deleted: 'Deleted at',
    workOffForm: 'Work-off from',
    workOffTo: 'Work-off to',
    reason: 'Reason',
    no: 'No',
    yes: 'Yes',
    unknown: 'Unknown',
    workedOut: 'Worked out',
    selectType: 'Select type',
    dateOffDate: 'Date-off date',
    firstHalf: 'First half',
    secondHalf: 'Second half',
    dayOffType: 'Day-off type',
    workOffType: 'Work-off type',
    workOffDate: 'Work-off date',
    uploadDocument: 'Upload document',
    weekdays: {
      Mon: 'Mon',
      Tue: 'Tue',
      Wed: 'Wed',
      Thu: 'Thu',
      Fri: 'Fri',
      Sat: 'Sat',
      Sun: 'Sun',
    },
    fromSickLeave: 'From',
    attachment: 'Attachment',
  },
  ru: {
    vacation: 'Отпуск',
    sickLeave: 'Больничный лист',
    dayOff: 'Отгул',
    halfDayOff: 'Полдня отгула',
    workOff: 'Отработка',
    holiday: 'Нерабочий день',
    'sick-leave': 'Больничный лист',
    'day-off': 'Отгул',
    'half-day-off': 'Полдня отгула',
    'work-off': 'Отработка',
    add: 'Добавить',
    employeeName: 'Имя сотрудника',
    vacationType: 'Тип отпуска',
    noVacations: 'Нет активных отпусков',
    selectVacationType: 'Выберите тип отпуска',
    addSickLeave: 'Больничный',
    addVacation: 'Отпуск',
    addDayOff: 'Отгул',
    addHalfDayOff: 'Полдня выходного',
    employee: 'Сотрудник',
    status: 'Статус',
    selectVacationStatus: 'Выберите статус отпуска',
    created: 'Создан в',
    updated: 'Обновлено в',
    deleted: 'Удален в',
    workOffForm: 'Отработка c',
    workOffTo: 'Отработка до',
    reason: 'Причина',
    no: 'Нет',
    yes: 'Да',
    unknown: 'Неизвестно',
    workedOut: 'Отработано',
    selectType: 'Выберите тип',
    dateOffDate: 'Дата выходного дня',
    dayOffType: 'Тип выходного дня',
    workOffType: 'Тип отработки',
    firstHalf: 'Первая половина',
    secondHalf: 'Вторая половина',
    workOffDate: 'Дата отработки',
    uploadDocument: 'Загрузить документ',
    weekdays: {
      Mon: 'Пн',
      Tue: 'Вт',
      Wed: 'Ср',
      Thu: 'Чт',
      Fri: 'Пт',
      Sat: 'Сб',
      Sun: 'Вс',
    },
    fromSickLeave: 'С',
    attachment: 'Вложение',
  },
};
